repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        exclude_types: [markdown, yaml]
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.4.0
    hooks:
      - id: stylelint
        args: [--fix]
        additional_dependencies:
          # stylelint itself needs to be here when using additional_dependencies.
          - stylelint@14.14.0
          - stylelint-config-standard@29.0.0
          - stylelint-config-rational-order@0.1.2
