name: Deploy to GitHub pages

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set fontawesome token
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.NPM_FA_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "out/"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        name: Deploy to GitHub pages
        uses: actions/deploy-pages@v2
